version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      node:
        condition: service_healthy   # ✅ healthcheck 기반 의존
    restart: unless-stopped          # (옵션) nginx 재시작 정책

  node:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./public:/app/public
      - /home/tslinux0101/uploads-data:/app/public/uploads  # ✅ 절대 경로로 수정
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    healthcheck:                    # ✅ node 서비스 준비 확인용
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Tsrtmd@3300
      MYSQL_DATABASE: project_301_db
    ports:
      - "3307:3306"
    volumes:
      - /home/tslinux0101/mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

volumes:
  mysql_data:
